behat.yml.dist, composer.json, tests/features/editorial_workflow.feature
=> OPENEUROPA-1522: Make sure we don't use Drupal paths in Behat scenarios.

.drone.yml, composer.json
=> OPENEUROPA-1533: Add --strict flag for Behat tests execution.

.drone.yml, behat.yml.dist, composer.json, docker-compose.yml, modules/oe_editorial_content_lock/README.md, modules/oe_editorial_content_lock/oe_editorial_content_lock.info.yml, modules/oe_editorial_content_lock/oe_editorial_content_lock.install, runner.yml.dist, tests/Behat/ContentLockContext.php, tests/Behat/FeatureContext.php, tests/features/content_lock.feature
Provide a module that prevents content from being edited by two editors at the same time.
- Added: oe_editorial_content_lock module
=> OPENEUROPA-1503: Add content lock module.

modules/oe_editorial_corporate_workflow/oe_editorial_corporate_workflow.module
=> Fixing the menu local task alter moderation check.

CHANGELOG.md
Create release 0.2.0.
- Added:
- Changed: Changelog.md
- Deprecated:
- Removed:
- Fixed:
- Security:
=> OPENEUROPA-1813: Create release 0.2.0.

CHANGELOG.md
- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```
=> OPENEUROPA-1864: Update Changelog for release 1.0.0-beta1.

composer.json, modules/oe_editorial_entity_version/oe_editorial_entity_version.install, tests/features/content_version.feature
First this PR has to be merged! https://github.com/openeuropa/entity_version/pull/9
=> OPENEUROPA-2037: Integrate the new config setting entity version.

CHANGELOG.md
Release 1.0.0: Update changelog.
- Changed: Changelog.
=> Release 1.0.0: Update changelog.

CHANGELOG.md
- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```
=> OPENEUROPA-0000: Update changelog for release.

modules/oe_editorial_corporate_workflow/src/CorporateWorkflowInstaller.php, tests/features/editorial_workflow.feature
- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```
=> OPENEUROPA-2754: Remove permissions for reverting/deleting revisions.

.drone.yml, composer.json, docker-compose.yml
- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```
=> OPENEUROPA-2941: Update php version.

.drone.yml, composer.json, docker-compose.yml, runner.yml.dist
Updating the component to ensure Poetry related tests work with the new changes in the oe_translation component.
=> OPENEUROPA-3012: Poetry translation updates.

CHANGELOG.md
Prepare release 1.6.0.
- Added:
- Changed: Update changelog for 1.6.0
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```
=> Prepare release 1.6.0.

CHANGELOG.md, composer.json, modules/oe_editorial_corporate_workflow/modules/oe_editorial_corporate_workflow_translation/modules/oe_editorial_corporate_workflow_translation_poetry/src/EventSubscriber/PoetryRequestTypeSubscriber.php
- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```
=> EWPP-0000: Preparing for 1.8.0 release.

modules/oe_editorial_corporate_workflow/modules/oe_editorial_corporate_workflow_translation/oe_editorial_corporate_workflow_translation.module, modules/oe_editorial_corporate_workflow/src/EntityStateTransitionBatch.php
See https://www.drupal.org/node/2664290 .
=> EWPP-1347: Do not typehint batch callback context parameter.

CHANGELOG.md
Prepare release 1.11.0.
- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```
=> Prepare release 1.11.0.

CHANGELOG.md
Prepare release 1.13.0.
- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```
=> Prepare release 1.13.0.

CHANGELOG.md
- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```
=> Prepare release 1.14.0.

CHANGELOG.md
- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```
=> Prepare release 1.14.1.

composer.json
- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```
=> EWPP-0000: Solve conflict with oe_translation dependency.

CHANGELOG.md
- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```
=> EWPP-0000: Prepare for release 1.14.2.

composer.json
- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```
=> EWPP: Fix ctools version.

CHANGELOG.md
- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```
=> Prepare release 1.15.0.

CHANGELOG.md, composer.json
- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```
=> Prepare release 1.15.1.
